#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Print a centered logon message
function center-text() {
colcount=$((`tput cols` - 1))
  sed  -e :a -e "s/^.\{1,$colcount\}$/ & /;ta"
}

if (( $+commands[adage] )); then
  if [[ -t 0 || -t 1 ]]; then
    adage | center-text
  fi
fi
